//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waTestaValidacaoC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoComposto", Namespace="http://schemas.datacontract.org/2004/07/WcfValidacao")]
    [System.SerializableAttribute()]
    public partial class TipoComposto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValorBooleanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValorDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValorBoolean {
            get {
                return this.ValorBooleanField;
            }
            set {
                if ((this.ValorBooleanField.Equals(value) != true)) {
                    this.ValorBooleanField = value;
                    this.RaisePropertyChanged("ValorBoolean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValorDate {
            get {
                return this.ValorDateField;
            }
            set {
                if ((this.ValorDateField.Equals(value) != true)) {
                    this.ValorDateField = value;
                    this.RaisePropertyChanged("ValorDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorString {
            get {
                return this.ValorStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorStringField, value) != true)) {
                    this.ValorStringField = value;
                    this.RaisePropertyChanged("ValorString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IValidacao")]
    public interface IValidacao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ObterDados", ReplyAction="http://tempuri.org/IValidacao/ObterDadosResponse")]
        string ObterDados(int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ObterDados", ReplyAction="http://tempuri.org/IValidacao/ObterDadosResponse")]
        System.Threading.Tasks.Task<string> ObterDadosAsync(int valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ObterDadosUsandoContratoDeDados", ReplyAction="http://tempuri.org/IValidacao/ObterDadosUsandoContratoDeDadosResponse")]
        waTestaValidacaoC.ServiceReference1.TipoComposto ObterDadosUsandoContratoDeDados(waTestaValidacaoC.ServiceReference1.TipoComposto composicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ObterDadosUsandoContratoDeDados", ReplyAction="http://tempuri.org/IValidacao/ObterDadosUsandoContratoDeDadosResponse")]
        System.Threading.Tasks.Task<waTestaValidacaoC.ServiceReference1.TipoComposto> ObterDadosUsandoContratoDeDadosAsync(waTestaValidacaoC.ServiceReference1.TipoComposto composicao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarNomesUsuarios", ReplyAction="http://tempuri.org/IValidacao/ValidarNomesUsuariosResponse")]
        bool ValidarNomesUsuarios(string nomeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarNomesUsuarios", ReplyAction="http://tempuri.org/IValidacao/ValidarNomesUsuariosResponse")]
        System.Threading.Tasks.Task<bool> ValidarNomesUsuariosAsync(string nomeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarNumerosTelefonicos", ReplyAction="http://tempuri.org/IValidacao/ValidarNumerosTelefonicosResponse")]
        bool ValidarNumerosTelefonicos(string numeroTelefonico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarNumerosTelefonicos", ReplyAction="http://tempuri.org/IValidacao/ValidarNumerosTelefonicosResponse")]
        System.Threading.Tasks.Task<bool> ValidarNumerosTelefonicosAsync(string numeroTelefonico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarEmail", ReplyAction="http://tempuri.org/IValidacao/ValidarEmailResponse")]
        bool ValidarEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarEmail", ReplyAction="http://tempuri.org/IValidacao/ValidarEmailResponse")]
        System.Threading.Tasks.Task<bool> ValidarEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarCodigosPostais", ReplyAction="http://tempuri.org/IValidacao/ValidarCodigosPostaisResponse")]
        bool ValidarCodigosPostais(string codigoPostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarCodigosPostais", ReplyAction="http://tempuri.org/IValidacao/ValidarCodigosPostaisResponse")]
        System.Threading.Tasks.Task<bool> ValidarCodigosPostaisAsync(string codigoPostal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarEnderecosIP", ReplyAction="http://tempuri.org/IValidacao/ValidarEnderecosIPResponse")]
        bool ValidarEnderecosIP(string EnderecoIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarEnderecosIP", ReplyAction="http://tempuri.org/IValidacao/ValidarEnderecosIPResponse")]
        System.Threading.Tasks.Task<bool> ValidarEnderecosIPAsync(string EnderecoIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarCoresHexadecimais", ReplyAction="http://tempuri.org/IValidacao/ValidarCoresHexadecimaisResponse")]
        bool ValidarCoresHexadecimais(string corHexadecimal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarCoresHexadecimais", ReplyAction="http://tempuri.org/IValidacao/ValidarCoresHexadecimaisResponse")]
        System.Threading.Tasks.Task<bool> ValidarCoresHexadecimaisAsync(string corHexadecimal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarComentariosMultiLinha", ReplyAction="http://tempuri.org/IValidacao/ValidarComentariosMultiLinhaResponse")]
        bool ValidarComentariosMultiLinha(string comentarioMultiLinha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarComentariosMultiLinha", ReplyAction="http://tempuri.org/IValidacao/ValidarComentariosMultiLinhaResponse")]
        System.Threading.Tasks.Task<bool> ValidarComentariosMultiLinhaAsync(string comentarioMultiLinha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarDatas", ReplyAction="http://tempuri.org/IValidacao/ValidarDatasResponse")]
        bool ValidarDatas(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidacao/ValidarDatas", ReplyAction="http://tempuri.org/IValidacao/ValidarDatasResponse")]
        System.Threading.Tasks.Task<bool> ValidarDatasAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidacaoChannel : waTestaValidacaoC.ServiceReference1.IValidacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidacaoClient : System.ServiceModel.ClientBase<waTestaValidacaoC.ServiceReference1.IValidacao>, waTestaValidacaoC.ServiceReference1.IValidacao {
        
        public ValidacaoClient() {
        }
        
        public ValidacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ObterDados(int valor) {
            return base.Channel.ObterDados(valor);
        }
        
        public System.Threading.Tasks.Task<string> ObterDadosAsync(int valor) {
            return base.Channel.ObterDadosAsync(valor);
        }
        
        public waTestaValidacaoC.ServiceReference1.TipoComposto ObterDadosUsandoContratoDeDados(waTestaValidacaoC.ServiceReference1.TipoComposto composicao) {
            return base.Channel.ObterDadosUsandoContratoDeDados(composicao);
        }
        
        public System.Threading.Tasks.Task<waTestaValidacaoC.ServiceReference1.TipoComposto> ObterDadosUsandoContratoDeDadosAsync(waTestaValidacaoC.ServiceReference1.TipoComposto composicao) {
            return base.Channel.ObterDadosUsandoContratoDeDadosAsync(composicao);
        }
        
        public bool ValidarNomesUsuarios(string nomeUsuario) {
            return base.Channel.ValidarNomesUsuarios(nomeUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNomesUsuariosAsync(string nomeUsuario) {
            return base.Channel.ValidarNomesUsuariosAsync(nomeUsuario);
        }
        
        public bool ValidarNumerosTelefonicos(string numeroTelefonico) {
            return base.Channel.ValidarNumerosTelefonicos(numeroTelefonico);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarNumerosTelefonicosAsync(string numeroTelefonico) {
            return base.Channel.ValidarNumerosTelefonicosAsync(numeroTelefonico);
        }
        
        public bool ValidarEmail(string email) {
            return base.Channel.ValidarEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarEmailAsync(string email) {
            return base.Channel.ValidarEmailAsync(email);
        }
        
        public bool ValidarCodigosPostais(string codigoPostal) {
            return base.Channel.ValidarCodigosPostais(codigoPostal);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCodigosPostaisAsync(string codigoPostal) {
            return base.Channel.ValidarCodigosPostaisAsync(codigoPostal);
        }
        
        public bool ValidarEnderecosIP(string EnderecoIP) {
            return base.Channel.ValidarEnderecosIP(EnderecoIP);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarEnderecosIPAsync(string EnderecoIP) {
            return base.Channel.ValidarEnderecosIPAsync(EnderecoIP);
        }
        
        public bool ValidarCoresHexadecimais(string corHexadecimal) {
            return base.Channel.ValidarCoresHexadecimais(corHexadecimal);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarCoresHexadecimaisAsync(string corHexadecimal) {
            return base.Channel.ValidarCoresHexadecimaisAsync(corHexadecimal);
        }
        
        public bool ValidarComentariosMultiLinha(string comentarioMultiLinha) {
            return base.Channel.ValidarComentariosMultiLinha(comentarioMultiLinha);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarComentariosMultiLinhaAsync(string comentarioMultiLinha) {
            return base.Channel.ValidarComentariosMultiLinhaAsync(comentarioMultiLinha);
        }
        
        public bool ValidarDatas(string data) {
            return base.Channel.ValidarDatas(data);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarDatasAsync(string data) {
            return base.Channel.ValidarDatasAsync(data);
        }
    }
}
